DROP TABLE IF EXISTS "attempt_ticket" CASCADE;
DROP TABLE IF EXISTS "question" CASCADE;
DROP TABLE IF EXISTS "question_sign" CASCADE;
DROP TABLE IF EXISTS "question_traffic_light" CASCADE;
DROP TABLE IF EXISTS "question_traffic_participant" CASCADE;
DROP TABLE IF EXISTS "sign" CASCADE;
DROP TABLE IF EXISTS "statistic" CASCADE;
DROP TABLE IF EXISTS "ticket" CASCADE;
DROP TABLE IF EXISTS "ticket_question" CASCADE;
DROP TABLE IF EXISTS "traffic_light" CASCADE;
DROP TABLE IF EXISTS "traffic_participant" CASCADE;
DROP TABLE IF EXISTS "attempt_question" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

